require("completition.blade.conditional")
require("completition.blade.date")
require("completition.blade.auth")
require("completition.blade.env")
require("completition.blade.section")
require("completition.blade.session")
require("completition.blade.switch")
require("completition.blade.loops")
require("completition.blade.classstyle")
require("completition.blade.AdditionalAttributes")
require("completition.blade.Subviews")
require("completition.blade.once")
require("completition.blade.php")
require("completition.blade.TemplateInheritance")
require("completition.blade.form")
require("completition.blade.injectandfragment")

